version: "3.7"
services:
  pocketbase:
    build:
      context: .
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: P@ssw0rd #optional your PW
    ports:
      - "8090:8090"
    volumes:
      - ./data:/pb_data
      - ./public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
